# Generated by Django 5.2 on 2025-04-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='paginas',
            field=models.IntegerField(default=100, max_length=40000000000),
            preserve_default=False,
        ),
    ]
