# Generated by Django 4.2 on 2025-04-04 13:55

from django.db import migrations, models
import livros.models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_paginas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='paginas',
            field=models.IntegerField(default=livros.models.default_paginas),
        ),
    ]
